- hosts: localhost

  vars:
    crio_version: 1.18
    apiserver: --kube-apiserver-arg=feature-gates=LocalStorageCapacityIsolation=false
    disable: --flannel-backend=none --disable=servicelb --disable=traefik
    datastore: --datastore-endpoint=postgres://${K3DB_USER}:${K3DB_PASSWORD}@localhost/${K3DB_DATABASE}?sslmode=disable
    runtime: --container-runtime-endpoint=unix:///run/crio/crio.sock
    storage: /data

  tasks:

  - name: Enable cri-o module
    command:
      cmd: dnf -y module enable cri-o:{{ crio_version }}
      warn: false

  - name: Install requirements
    dnf:
      name:
      - container-selinux
      - cri-o
      - iptables-nft
      - postgresql-server
      - selinux-policy-base
      state: latest

  - name: Set crio cgroup_manager
    lineinfile:
      path: /etc/crio/crio.conf
      regex: ^cgroup_manager
      line: cgroup_manager = "cgroupfs"

  - name: Set containers storage_driver
    lineinfile:
      path: /etc/containers/storage.conf
      regex: ^storage_driver
      line: storage_driver = "btrfs"

  - name: Add registries to crio.conf
    blockinfile:
      path: /etc/crio/crio.conf
      block: |
        registries = [
          "docker.io"
        ]

  - name: Add network_dir to crio.conf
    lineinfile:
      path: /etc/crio/crio.conf
      regex: ^network_dir
      line: network_dir = "/var/lib/rancher/k3s/agent/etc/cni/net.d/"

  - name: Make storage directory
    file:
      path: "{{ storage }}"
      state: directory
      owner: root
      group: root
      mode: '0755'

  - name: Add script k3ckstart.sh
    copy:
      dest: /usr/local/sbin/k3ckstart.sh
      src: files/k3ckstart.sh
      owner: root
      group: root
      mode: 0750

  - name: Add k3ckstart.service
    copy:
      dest: /etc/systemd/system/k3ckstart.service
      src: files/k3ckstart.service
      owner: root
      group: root
      mode: 0644

  - name: Add postgresql-setup.sh
    copy:
      dest: /usr/local/bin/postgresql-setup.sh
      src: files/postgresql-setup.sh
      owner: root
      group: root
      mode: 0755

  - name: Add postgresql-setup.service
    copy:
      dest: /etc/systemd/system/postgresql-setup.service
      src: files/postgresql-setup.service
      owner: root
      group: root
      mode: 0644

  - name: Enable postgresql-setup.service
    file:
      src: /etc/systemd/system/postgresql-setup.service
      dest: /etc/systemd/system/multi-user.target.wants/postgresql-setup.service
      state: link

  - name: Enable postgresql.service
    file:
      src: /usr/lib/systemd/system/postgresql.service
      dest: /etc/systemd/system/multi-user.target.wants/postgresql.service
      state: link

  - name: Install k3s-selinux
    dnf:
      name: https://rpm.rancher.io/k3s-selinux-0.1.1-rc1.el7.noarch.rpm
      disable_gpg_check: true
      state: present

  - name: Download k3s installation script
    get_url:
      url: https://get.k3s.io
      dest: /tmp/install_k3s.sh

  - name: Set k3s installation script permissions
    file:
      path: /tmp/install_k3s.sh
      owner: root
      group: root
      mode: '0755'

  - name: Execute k3s installation script
    shell:
      cmd: /tmp/install_k3s.sh
    environment:
      INSTALL_K3S_SKIP_START: "true"
      INSTALL_K3S_EXEC: "{{ apiserver }} {{ datastore }} {{ runtime }} {{ disable }} --default-local-storage-path={{ storage }}"

  - name: Add cri-o/postgresql dependency to k3s.service
    lineinfile:
      path: /etc/systemd/system/k3s.service
      regex: ^Wants=
      line: Requires=cri-o.service k3ckstart.service postgresql.service

  - name: Allow vars in k3s.service
    lineinfile:
      path: /etc/systemd/system/k3s.service
      regex: --datastore-endpoint
      line: '        "{{ datastore }}" \'

  - name: Remove modprobe from k3s.service
    lineinfile:
      path: /etc/systemd/system/k3s.service
      regex: modprobe
      state: absent

  - name: Remove k3s installation script
    file:
      path: /tmp/install_k3s.sh
      state: absent

  - name: mkdir /var/lib/rancher/k3s/server/manifests
    file:
      path: /var/lib/rancher/k3s/server/manifests
      state: directory
      owner: root
      group: root
      mode: '0755'
